version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/mongodb/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./mongodb/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet